package dev.relaypatch.app.data.model

import kotlinx.serialization.Serializable

/**
 * Wire-format envelope pushed to the VS Code companion via the Bridge Layer.
 *
 * Matches the JSON schema documented in TECHNICAL_DOC.md §2.4:
 * ```json
 * { "id": "...", "diffText": "...", "targetFileHint": "..." }
 * ```
 *
 * @property id             Unique patch identifier (UUID).
 * @property diffText       Unified diff generated by the local LLM.
 * @property targetFileHint Optional file path hint surfaced to the VS Code companion
 *                          so it can pre-select the correct editor tab.
 */
@Serializable
data class PatchPayload(
    val id: String,
    val diffText: String,
    val targetFileHint: String?,
)
